<a href="https://colab.research.google.com/github/TKM-MCA-2020-DATA-SCIENCE-LAB/20MCA301-ABHILASH_JOHN/blob/master/01_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ls = [1,4,3]
np.array(ls)

array([1, 4, 3])

In [ ]:
ls2 = [[1,2,3],[1,2,3],[4,5,7]]
np.array(ls2)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 7]])

In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
np.random.rand()

0.6693150528794439

In [ ]:
np.random.rand(1)

array([0.58091202])

In [ ]:
np.random.rand(1,2)

array([[0.36425407, 0.78117433]])

In [ ]:
np.random.randn()

-0.11354409810955991

In [ ]:
np.random.randint(1,8)

4

In [ ]:
np.random.randint(1,8,10)

array([7, 4, 1, 5, 4, 7, 7, 3, 1, 6])

Array Attributes and Methods

In [ ]:
arr= np.arange(25)
randarr= np.random.randint(1,100,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
randarr

array([67,  5,  4, 48, 72])

In [ ]:
randarr.min()

4

In [ ]:
randarr.max()

72

In [ ]:
randarr.argmax()

4

In [ ]:
randarr.argmin()

2

In [ ]:

randarr.shape

(5,)

In [ ]:
randarr.dtype

dtype('int64')

In [ ]:

randarr[1]

5

In [ ]:
ls2 = [[1,2,3],[1,2,3],[4,5,7]]
ls2[1:3]

[[1, 2, 3], [4, 5, 7]]

In [ ]:
ls2=np.array(ls2)


In [ ]:
ls2

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 7]])

In [ ]:
ls2[1:2]

array([[1, 2, 3]])

In [ ]:
ls2[1:2]

# **Selection**


In [ ]:
y = ls2[:,0] = 1
ls2[y,:]

array([1, 2, 3])